// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.pedidoaberto.pedidos
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class NovoPedido : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"NovoPedido\",\"namespace\":\"com.pedidoaberto.pedidos\",\"fiel" +
				"ds\":[{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"nome\",\"type\":\"string\"},{\"name\":\"for" +
				"necedor\",\"type\":\"string\"},{\"name\":\"vendedor\",\"type\":\"string\"}]}");
		private string _sku;
		private string _nome;
		private string _fornecedor;
		private string _vendedor;
		public virtual Schema Schema
		{
			get
			{
				return NovoPedido._SCHEMA;
			}
		}
		public string sku
		{
			get
			{
				return this._sku;
			}
			set
			{
				this._sku = value;
			}
		}
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		public string fornecedor
		{
			get
			{
				return this._fornecedor;
			}
			set
			{
				this._fornecedor = value;
			}
		}
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				this._vendedor = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.sku;
			case 1: return this.nome;
			case 2: return this.fornecedor;
			case 3: return this.vendedor;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.sku = (System.String)fieldValue; break;
			case 1: this.nome = (System.String)fieldValue; break;
			case 2: this.fornecedor = (System.String)fieldValue; break;
			case 3: this.vendedor = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
